### ISSUE TITLE
CMake script section

### ISSUE THREAD

**Issue by OlivierLDff** [mikalv/awesome-qt-qml#23]
Hello i don't see lots of link to CMake based project so i want to share some cmake script:
* [QtIosCMake](https://github.com/OlivierLDff/QtIosCMake): Deploy Qt Application for iOS with a single macro when using CMake.
* [qt-android-cmake](https://github.com/LaurentGomila/qt-android-cmake): Deploy Qt Application for Android with a single macro when using CMake.
* [QtWindowsCMake](https://github.com/OlivierLDff/QtWindowsCMake):  Deploy Qt Application for Windows with a single macro when using CMake.
* [QtStaticCMake](https://github.com/OlivierLDff/QtStaticCMake) : Easy deploy qt and qml app with a static version of qt.
* [QtWasmCMake](https://github.com/OlivierLDff/QtWasmCMake) : Deploy Qt Application for WebAssembly with a single function when using CMake.
* [QQuickStaticHelloWorld](https://github.com/OlivierLDff/QQuickStaticHelloWorld) : Template qt quick app with cmake that is ready to be used with static qt.

Update:
* [QtGeneratorCMake](https://github.com/OlivierLDff/QtGeneratorCMake) : Generate qrc, qmldir at cmake time
* [FetchGoogleFontCMake](https://github.com/OlivierLDff/FetchGoogleFontCMake): Download font from google font repo. Should be combined with QtGeneratorCMake to easily embed font to qrc.

**Comment by mikalv** [comment]
please make a PR :)
