### ISSUE TITLE
A few suggestions to the learning section

### ISSUE THREAD

**Issue by jesperkdab** [mikalv/awesome-qt-qml#26]
Hi.
May I suggest the complete QML training that we (KDAB) have put up on youtube for free:
https://www.youtube.com/watch?v=JxyTkXLbcV4&list=PL6CJYn40gN6hdNC1IGQZfVI707dh9DPRc

Also, I am hosting a youtube series on Qt Widgets development, which might be interesting to people wanting to learn more about Qt:
https://www.youtube.com/watch?v=X116W8Uk9Wk&list=PL6CJYn40gN6gf-G-o6syFwGrtq3kItEqI

Cheers
Jesper.

**Comment by nrbnlulu** [comment]
Awesome series  thanks Jesper!

**Comment by mikalv** [comment]
please make a PR :)
