### ISSUE TITLE
Provide new examples

### ISSUE THREAD

**Issue by qyvlik** [mikalv/awesome-qt-qml#3]
[qyvlik/ShaderToy.qml](https://github.com/qyvlik/ShaderToy.qml)

> ShaderToy demo by QML.

**Comment by qyvlik** [comment]
Add new [188080501/JQTools](https://github.com/188080501/JQTools)

> Qt Tools  ![](https://github.com/188080501/JQTools/raw/master/preview/JQToolsPreview.png)

**Comment by mikalv** [comment]
please make a PR :)
